import { IconSets } from './types/index'

export const icons = [
  { iconName: 'motorcycle', displayName: 'motorcycle', iconNameSet: IconSets.FA },
  { iconName: 'flag', displayName: 'flag', iconNameSet: IconSets.FA },
  { iconName: 'bus', displayName: 'bus', iconNameSet: IconSets.FA5 },
  { iconName: 'train', displayName: 'train', iconNameSet: IconSets.FA },
  { iconName: 'truck', displayName: 'truck', iconNameSet: IconSets.FA },
  { iconName: 'dump-truck', displayName: 'dump truck', iconNameSet: IconSets.MCI },
  { iconName: 'fire-truck', displayName: 'fire-truck', iconNameSet: IconSets.MCI },
  { iconName: 'plane', displayName: 'plane', iconNameSet: IconSets.FA },
  { iconName: 'bell', displayName: 'bell', iconNameSet: IconSets.FA },
  { iconName: 'mobile', displayName: 'cell phone', iconNameSet: IconSets.FA },
  { iconName: 'trash', displayName: 'trash can', iconNameSet: IconSets.FA },
  { iconName: 'bicycle', displayName: 'bicycle', iconNameSet: IconSets.FA },
  { iconName: 'car', displayName: 'car', iconNameSet: IconSets.FA },
  { iconName: 'building', displayName: 'building', iconNameSet: IconSets.FA5 },
  { iconName: 'hospital-building', displayName: 'hospital', iconNameSet: IconSets.MCI },
  { iconName: 'home', displayName: 'home', iconNameSet: IconSets.FA },
  { iconName: 'child', displayName: 'child', iconNameSet: IconSets.FA },
  { iconName: 'hotel', displayName: 'hotel', iconNameSet: IconSets.FA },
  { iconName: 'ship', displayName: 'boat', iconNameSet: IconSets.FA5 },
  { iconName: 'dove', displayName: 'bird', iconNameSet: IconSets.FA5 },
  { iconName: 'baby', displayName: 'baby', iconNameSet: IconSets.FA5 },
  { iconName: 'baby-carriage', displayName: 'stroller', iconNameSet: IconSets.FA5 },
  { iconName: 'mountain', displayName: 'mountain', iconNameSet: IconSets.FA5 },
  { iconName: 'shopping-cart', displayName: 'cart', iconNameSet: IconSets.FA5 },
  { iconName: 'box-open', displayName: 'box', iconNameSet: IconSets.FA5 },
  { iconName: 'cloud', displayName: 'cloud', iconNameSet: IconSets.FA5 },
  { iconName: 'cloud-rain', displayName: 'rain', iconNameSet: IconSets.FA5 },
  { iconName: 'camera', displayName: 'camera', iconNameSet: IconSets.FA },
  { iconName: 'bug', displayName: 'insect', iconNameSet: IconSets.FA5 },
  { iconName: 'flower', displayName: 'flower', iconNameSet: IconSets.MCI },
  { iconName: 'bucket', displayName: 'bucket', iconNameSet: IconSets.ENTYPO },
  { iconName: 'star', displayName: 'star', iconNameSet: IconSets.FA },
  { iconName: 'rainbow', displayName: 'rainbow', iconNameSet: IconSets.ENTYPO },
  { iconName: 'tools', displayName: 'tools', iconNameSet: IconSets.ENTYPO },
  { iconName: 'suitcase', displayName: 'luggage', iconNameSet: IconSets.FA },
  { iconName: 'clock', displayName: 'clock', iconNameSet: IconSets.FA5 },
  { iconName: 'shop', displayName: 'store', iconNameSet: IconSets.ENTYPO },
  { iconName: 'traffic-cone', displayName: 'traffic cone', iconNameSet: IconSets.ENTYPO },
  { iconName: 'traffic-light', displayName: 'traffic light', iconNameSet: IconSets.FA5 },
  { iconName: 'cutlery', displayName: 'restuarant', iconNameSet: IconSets.FA },
  { iconName: 'apple-alt', displayName: 'fruit', iconNameSet: IconSets.FA5 },
  { iconName: 'tree', displayName: 'forest', iconNameSet: IconSets.FA },
  { iconName: 'soccer-ball-o', displayName: 'ball', iconNameSet: IconSets.FA },
  { iconName: 'industry', displayName: 'factory', iconNameSet: IconSets.FA5 },
  { iconName: 'water', displayName: 'water', iconNameSet: IconSets.FA5 },
  { iconName: 'ambulance', displayName: 'ambulance', iconNameSet: IconSets.FA5 },
  { iconName: 'book', displayName: 'book', iconNameSet: IconSets.FA5 },
  { iconName: 'campground', displayName: 'campground', iconNameSet: IconSets.FA5 },
  { iconName: 'broadcast-tower', displayName: 'radio tower', iconNameSet: IconSets.FA5 },
  { iconName: 'cat', displayName: 'cat', iconNameSet: IconSets.FA5 },
  { iconName: 'dog', displayName: 'dog', iconNameSet: IconSets.FA5 },
  { iconName: 'church', displayName: 'church', iconNameSet: IconSets.FA5 },
  { iconName: 'city', displayName: 'city', iconNameSet: IconSets.MCI },
  { iconName: 'gas-pump', displayName: 'gas station', iconNameSet: IconSets.FA5 },
  { iconName: 'horse', displayName: 'horse', iconNameSet: IconSets.FA5 },
  { iconName: 'coffee', displayName: 'coffee', iconNameSet: IconSets.FA },
  { iconName: 'pizza', displayName: 'pizzaa', iconNameSet: IconSets.FA5 },
  { iconName: 'road', displayName: 'road', iconNameSet: IconSets.FA5 },
  { iconName: 'school', displayName: 'school', iconNameSet: IconSets.FA5 },
  { iconName: 'tractor', displayName: 'tractor', iconNameSet: IconSets.FA5 },
  { iconName: 'bridge', displayName: 'bridge', iconNameSet: IconSets.MCI },
  { iconName: 'pool', displayName: 'pool', iconNameSet: IconSets.MCI },
  { iconName: 'stadium', displayName: 'stadium', iconNameSet: IconSets.MCI }
]
